// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (user_id, category_id, name, description, total_amount, remaining_amount,
                   interest_rate, total_installments, current_installment, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at
`

type CreateDebtParams struct {
	UserID             uuid.UUID      `json:"user_id"`
	CategoryID         pgtype.UUID    `json:"category_id"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	TotalAmount        pgtype.Numeric `json:"total_amount"`
	RemainingAmount    pgtype.Numeric `json:"remaining_amount"`
	InterestRate       pgtype.Numeric `json:"interest_rate"`
	TotalInstallments  int32          `json:"total_installments"`
	CurrentInstallment int32          `json:"current_installment"`
	Status             string         `json:"status"`
	StartDate          pgtype.Date    `json:"start_date"`
	EndDate            pgtype.Date    `json:"end_date"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.TotalAmount,
		arg.RemainingAmount,
		arg.InterestRate,
		arg.TotalInstallments,
		arg.CurrentInstallment,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.TotalInstallments,
		&i.CurrentInstallment,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = $1
`

func (q *Queries) DeleteDebt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDebt, id)
	return err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at FROM debts WHERE id = $1
`

func (q *Queries) GetDebtByID(ctx context.Context, id uuid.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.TotalInstallments,
		&i.CurrentInstallment,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDebtsByUserID = `-- name: ListActiveDebtsByUserID :many
SELECT id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at FROM debts WHERE user_id = $1 AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) ListActiveDebtsByUserID(ctx context.Context, userID uuid.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listActiveDebtsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.TotalAmount,
			&i.RemainingAmount,
			&i.InterestRate,
			&i.TotalInstallments,
			&i.CurrentInstallment,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByUserID = `-- name: ListDebtsByUserID :many
SELECT id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at FROM debts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDebtsByUserID(ctx context.Context, userID uuid.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.TotalAmount,
			&i.RemainingAmount,
			&i.InterestRate,
			&i.TotalInstallments,
			&i.CurrentInstallment,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    total_amount = COALESCE($4, total_amount),
    remaining_amount = COALESCE($5, remaining_amount),
    interest_rate = COALESCE($6, interest_rate),
    total_installments = COALESCE($7, total_installments),
    current_installment = COALESCE($8, current_installment),
    status = COALESCE($9, status),
    end_date = COALESCE($10, end_date),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at
`

type UpdateDebtParams struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	TotalAmount        pgtype.Numeric `json:"total_amount"`
	RemainingAmount    pgtype.Numeric `json:"remaining_amount"`
	InterestRate       pgtype.Numeric `json:"interest_rate"`
	TotalInstallments  int32          `json:"total_installments"`
	CurrentInstallment int32          `json:"current_installment"`
	Status             string         `json:"status"`
	EndDate            pgtype.Date    `json:"end_date"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebt,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TotalAmount,
		arg.RemainingAmount,
		arg.InterestRate,
		arg.TotalInstallments,
		arg.CurrentInstallment,
		arg.Status,
		arg.EndDate,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.TotalInstallments,
		&i.CurrentInstallment,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDebtCurrentInstallment = `-- name: UpdateDebtCurrentInstallment :one
UPDATE debts SET current_installment = $2, updated_at = now() WHERE id = $1 RETURNING id, user_id, category_id, name, description, total_amount, remaining_amount, interest_rate, total_installments, current_installment, status, start_date, end_date, created_at, updated_at
`

type UpdateDebtCurrentInstallmentParams struct {
	ID                 uuid.UUID `json:"id"`
	CurrentInstallment int32     `json:"current_installment"`
}

func (q *Queries) UpdateDebtCurrentInstallment(ctx context.Context, arg UpdateDebtCurrentInstallmentParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebtCurrentInstallment, arg.ID, arg.CurrentInstallment)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.TotalAmount,
		&i.RemainingAmount,
		&i.InterestRate,
		&i.TotalInstallments,
		&i.CurrentInstallment,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
