// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debt_monthly_status.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDebtMonthlyStatus = `-- name: CreateDebtMonthlyStatus :one
INSERT INTO debt_monthly_status (debt_id, month, installment_num, total_installments,
                                 amount_due, interest_amount, principal_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at
`

type CreateDebtMonthlyStatusParams struct {
	DebtID            uuid.UUID      `json:"debt_id"`
	Month             pgtype.Date    `json:"month"`
	InstallmentNum    int32          `json:"installment_num"`
	TotalInstallments int32          `json:"total_installments"`
	AmountDue         pgtype.Numeric `json:"amount_due"`
	InterestAmount    pgtype.Numeric `json:"interest_amount"`
	PrincipalAmount   pgtype.Numeric `json:"principal_amount"`
}

func (q *Queries) CreateDebtMonthlyStatus(ctx context.Context, arg CreateDebtMonthlyStatusParams) (DebtMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, createDebtMonthlyStatus,
		arg.DebtID,
		arg.Month,
		arg.InstallmentNum,
		arg.TotalInstallments,
		arg.AmountDue,
		arg.InterestAmount,
		arg.PrincipalAmount,
	)
	var i DebtMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Month,
		&i.InstallmentNum,
		&i.TotalInstallments,
		&i.AmountDue,
		&i.InterestAmount,
		&i.PrincipalAmount,
		&i.AmountPaid,
		&i.Paid,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnpaidByUserIDAndDateRange = `-- name: ListUnpaidByUserIDAndDateRange :many
SELECT dms.id, dms.debt_id, dms.month, dms.installment_num, dms.total_installments, dms.amount_due, dms.interest_amount, dms.principal_amount, dms.amount_paid, dms.paid, dms.paid_at, dms.notes, dms.created_at, dms.updated_at FROM debt_monthly_status dms
JOIN debts d ON d.id = dms.debt_id
WHERE d.user_id = $1
  AND d.status = 'active'
  AND dms.month >= $2
  AND dms.month < $3
  AND dms.paid = false
ORDER BY dms.month, dms.debt_id
`

type ListUnpaidByUserIDAndDateRangeParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Start   pgtype.Date `json:"start"`
	End     pgtype.Date `json:"end"`
}

func (q *Queries) ListUnpaidByUserIDAndDateRange(ctx context.Context, arg ListUnpaidByUserIDAndDateRangeParams) ([]DebtMonthlyStatus, error) {
	rows, err := q.db.Query(ctx, listUnpaidByUserIDAndDateRange, arg.UserID, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtMonthlyStatus{}
	for rows.Next() {
		var i DebtMonthlyStatus
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Month,
			&i.InstallmentNum,
			&i.TotalInstallments,
			&i.AmountDue,
			&i.InterestAmount,
			&i.PrincipalAmount,
			&i.AmountPaid,
			&i.Paid,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDebtMonthlyStatus = `-- name: DeleteDebtMonthlyStatus :exec
DELETE FROM debt_monthly_status WHERE id = $1
`

func (q *Queries) DeleteDebtMonthlyStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDebtMonthlyStatus, id)
	return err
}

const getDebtMonthlyStatus = `-- name: GetDebtMonthlyStatus :one
SELECT id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at FROM debt_monthly_status WHERE debt_id = $1 AND month = $2
`

type GetDebtMonthlyStatusParams struct {
	DebtID uuid.UUID   `json:"debt_id"`
	Month  pgtype.Date `json:"month"`
}

func (q *Queries) GetDebtMonthlyStatus(ctx context.Context, arg GetDebtMonthlyStatusParams) (DebtMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, getDebtMonthlyStatus, arg.DebtID, arg.Month)
	var i DebtMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Month,
		&i.InstallmentNum,
		&i.TotalInstallments,
		&i.AmountDue,
		&i.InterestAmount,
		&i.PrincipalAmount,
		&i.AmountPaid,
		&i.Paid,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDebtMonthlyStatusByDebtID = `-- name: ListDebtMonthlyStatusByDebtID :many
SELECT id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at FROM debt_monthly_status WHERE debt_id = $1 ORDER BY month DESC
`

func (q *Queries) ListDebtMonthlyStatusByDebtID(ctx context.Context, debtID uuid.UUID) ([]DebtMonthlyStatus, error) {
	rows, err := q.db.Query(ctx, listDebtMonthlyStatusByDebtID, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtMonthlyStatus{}
	for rows.Next() {
		var i DebtMonthlyStatus
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Month,
			&i.InstallmentNum,
			&i.TotalInstallments,
			&i.AmountDue,
			&i.InterestAmount,
			&i.PrincipalAmount,
			&i.AmountPaid,
			&i.Paid,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtMonthlyStatusByMonth = `-- name: ListDebtMonthlyStatusByMonth :many
SELECT id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at FROM debt_monthly_status WHERE month = $1 ORDER BY debt_id
`

func (q *Queries) ListDebtMonthlyStatusByMonth(ctx context.Context, month pgtype.Date) ([]DebtMonthlyStatus, error) {
	rows, err := q.db.Query(ctx, listDebtMonthlyStatusByMonth, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtMonthlyStatus{}
	for rows.Next() {
		var i DebtMonthlyStatus
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Month,
			&i.InstallmentNum,
			&i.TotalInstallments,
			&i.AmountDue,
			&i.InterestAmount,
			&i.PrincipalAmount,
			&i.AmountPaid,
			&i.Paid,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDebtMonthAsPaid = `-- name: MarkDebtMonthAsPaid :one
UPDATE debt_monthly_status
SET paid = true, paid_at = now(), amount_paid = $3, notes = COALESCE($4, notes), updated_at = now()
WHERE debt_id = $1 AND month = $2
RETURNING id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at
`

type MarkDebtMonthAsPaidParams struct {
	DebtID     uuid.UUID      `json:"debt_id"`
	Month      pgtype.Date    `json:"month"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) MarkDebtMonthAsPaid(ctx context.Context, arg MarkDebtMonthAsPaidParams) (DebtMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, markDebtMonthAsPaid,
		arg.DebtID,
		arg.Month,
		arg.AmountPaid,
		arg.Notes,
	)
	var i DebtMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Month,
		&i.InstallmentNum,
		&i.TotalInstallments,
		&i.AmountDue,
		&i.InterestAmount,
		&i.PrincipalAmount,
		&i.AmountPaid,
		&i.Paid,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDebtMonthlyStatus = `-- name: UpdateDebtMonthlyStatus :one
UPDATE debt_monthly_status
SET amount_paid = COALESCE($3, amount_paid),
    paid = $4,
    notes = COALESCE($5, notes),
    updated_at = now()
WHERE debt_id = $1 AND month = $2
RETURNING id, debt_id, month, installment_num, total_installments, amount_due, interest_amount, principal_amount, amount_paid, paid, paid_at, notes, created_at, updated_at
`

type UpdateDebtMonthlyStatusParams struct {
	DebtID     uuid.UUID      `json:"debt_id"`
	Month      pgtype.Date    `json:"month"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
	Paid       bool           `json:"paid"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateDebtMonthlyStatus(ctx context.Context, arg UpdateDebtMonthlyStatusParams) (DebtMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, updateDebtMonthlyStatus,
		arg.DebtID,
		arg.Month,
		arg.AmountPaid,
		arg.Paid,
		arg.Notes,
	)
	var i DebtMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Month,
		&i.InstallmentNum,
		&i.TotalInstallments,
		&i.AmountDue,
		&i.InterestAmount,
		&i.PrincipalAmount,
		&i.AmountPaid,
		&i.Paid,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
