// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_monthly_status.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseMonthlyStatus = `-- name: CreateExpenseMonthlyStatus :one
INSERT INTO expense_monthly_status (expense_id, month, amount_paid, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, expense_id, month, paid, paid_at, amount_paid, notes, created_at
`

type CreateExpenseMonthlyStatusParams struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	Month      pgtype.Date    `json:"month"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateExpenseMonthlyStatus(ctx context.Context, arg CreateExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, createExpenseMonthlyStatus,
		arg.ExpenseID,
		arg.Month,
		arg.AmountPaid,
		arg.Notes,
	)
	var i ExpenseMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Month,
		&i.Paid,
		&i.PaidAt,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseMonthlyStatus = `-- name: DeleteExpenseMonthlyStatus :exec
DELETE FROM expense_monthly_status WHERE id = $1
`

func (q *Queries) DeleteExpenseMonthlyStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseMonthlyStatus, id)
	return err
}

const getExpenseMonthlyStatus = `-- name: GetExpenseMonthlyStatus :one
SELECT id, expense_id, month, paid, paid_at, amount_paid, notes, created_at FROM expense_monthly_status WHERE expense_id = $1 AND month = $2
`

type GetExpenseMonthlyStatusParams struct {
	ExpenseID uuid.UUID   `json:"expense_id"`
	Month     pgtype.Date `json:"month"`
}

func (q *Queries) GetExpenseMonthlyStatus(ctx context.Context, arg GetExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, getExpenseMonthlyStatus, arg.ExpenseID, arg.Month)
	var i ExpenseMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Month,
		&i.Paid,
		&i.PaidAt,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenseMonthlyStatusByExpenseID = `-- name: ListExpenseMonthlyStatusByExpenseID :many
SELECT id, expense_id, month, paid, paid_at, amount_paid, notes, created_at FROM expense_monthly_status WHERE expense_id = $1 ORDER BY month DESC
`

func (q *Queries) ListExpenseMonthlyStatusByExpenseID(ctx context.Context, expenseID uuid.UUID) ([]ExpenseMonthlyStatus, error) {
	rows, err := q.db.Query(ctx, listExpenseMonthlyStatusByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseMonthlyStatus{}
	for rows.Next() {
		var i ExpenseMonthlyStatus
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.Month,
			&i.Paid,
			&i.PaidAt,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseMonthlyStatusByMonth = `-- name: ListExpenseMonthlyStatusByMonth :many
SELECT id, expense_id, month, paid, paid_at, amount_paid, notes, created_at FROM expense_monthly_status WHERE month = $1 ORDER BY expense_id
`

func (q *Queries) ListExpenseMonthlyStatusByMonth(ctx context.Context, month pgtype.Date) ([]ExpenseMonthlyStatus, error) {
	rows, err := q.db.Query(ctx, listExpenseMonthlyStatusByMonth, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseMonthlyStatus{}
	for rows.Next() {
		var i ExpenseMonthlyStatus
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.Month,
			&i.Paid,
			&i.PaidAt,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpenseMonthAsPaid = `-- name: MarkExpenseMonthAsPaid :one
UPDATE expense_monthly_status
SET paid = true, paid_at = now(), amount_paid = COALESCE($3, amount_paid), notes = COALESCE($4, notes)
WHERE expense_id = $1 AND month = $2
RETURNING id, expense_id, month, paid, paid_at, amount_paid, notes, created_at
`

type MarkExpenseMonthAsPaidParams struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	Month      pgtype.Date    `json:"month"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) MarkExpenseMonthAsPaid(ctx context.Context, arg MarkExpenseMonthAsPaidParams) (ExpenseMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, markExpenseMonthAsPaid,
		arg.ExpenseID,
		arg.Month,
		arg.AmountPaid,
		arg.Notes,
	)
	var i ExpenseMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Month,
		&i.Paid,
		&i.PaidAt,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExpenseMonthlyStatus = `-- name: UpsertExpenseMonthlyStatus :one
INSERT INTO expense_monthly_status (expense_id, month, paid, amount_paid, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (expense_id, month)
DO UPDATE SET paid = COALESCE($3, expense_monthly_status.paid),
              amount_paid = COALESCE($4, expense_monthly_status.amount_paid),
              paid_at = CASE WHEN $3 THEN now() ELSE expense_monthly_status.paid_at END,
              notes = COALESCE($5, expense_monthly_status.notes)
RETURNING id, expense_id, month, paid, paid_at, amount_paid, notes, created_at
`

type UpsertExpenseMonthlyStatusParams struct {
	ExpenseID  uuid.UUID      `json:"expense_id"`
	Month      pgtype.Date    `json:"month"`
	Paid       bool           `json:"paid"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) UpsertExpenseMonthlyStatus(ctx context.Context, arg UpsertExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error) {
	row := q.db.QueryRow(ctx, upsertExpenseMonthlyStatus,
		arg.ExpenseID,
		arg.Month,
		arg.Paid,
		arg.AmountPaid,
		arg.Notes,
	)
	var i ExpenseMonthlyStatus
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Month,
		&i.Paid,
		&i.PaidAt,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
