// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupExpiredInviteTokens = `-- name: CleanupExpiredInviteTokens :exec
DELETE FROM invite_tokens WHERE expires_at < NOW() OR used = true
`

func (q *Queries) CleanupExpiredInviteTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredInviteTokens)
	return err
}

const createInviteToken = `-- name: CreateInviteToken :one
INSERT INTO invite_tokens (token, created_by, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, created_by, used, expires_at, created_at
`

type CreateInviteTokenParams struct {
	Token     string    `json:"token"`
	CreatedBy uuid.UUID `json:"created_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error) {
	row := q.db.QueryRow(ctx, createInviteToken, arg.Token, arg.CreatedBy, arg.ExpiresAt)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteToken = `-- name: GetInviteToken :one
SELECT id, token, created_by, used, expires_at, created_at FROM invite_tokens WHERE token = $1
`

func (q *Queries) GetInviteToken(ctx context.Context, token string) (InviteToken, error) {
	row := q.db.QueryRow(ctx, getInviteToken, token)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInviteTokensByCreator = `-- name: ListInviteTokensByCreator :many
SELECT id, token, created_by, used, expires_at, created_at FROM invite_tokens WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInviteTokensByCreator(ctx context.Context, createdBy uuid.UUID) ([]InviteToken, error) {
	rows, err := q.db.Query(ctx, listInviteTokensByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteToken{}
	for rows.Next() {
		var i InviteToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.CreatedBy,
			&i.Used,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteTokenAsUsed = `-- name: MarkInviteTokenAsUsed :one
UPDATE invite_tokens SET used = true WHERE id = $1 RETURNING id, token, created_by, used, expires_at, created_at
`

func (q *Queries) MarkInviteTokenAsUsed(ctx context.Context, id uuid.UUID) (InviteToken, error) {
	row := q.db.QueryRow(ctx, markInviteTokenAsUsed, id)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedBy,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
