// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Icon      pgtype.Text `json:"icon"`
	Color     pgtype.Text `json:"color"`
	CreatedAt time.Time   `json:"created_at"`
}

type Debt struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	CategoryID         pgtype.UUID    `json:"category_id"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	TotalAmount        pgtype.Numeric `json:"total_amount"`
	RemainingAmount    pgtype.Numeric `json:"remaining_amount"`
	InterestRate       pgtype.Numeric `json:"interest_rate"`
	TotalInstallments  int32          `json:"total_installments"`
	CurrentInstallment int32          `json:"current_installment"`
	Status             string         `json:"status"`
	StartDate          pgtype.Date    `json:"start_date"`
	EndDate            pgtype.Date    `json:"end_date"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type DebtMonthlyStatus struct {
	ID                uuid.UUID          `json:"id"`
	DebtID            uuid.UUID          `json:"debt_id"`
	Month             pgtype.Date        `json:"month"`
	InstallmentNum    int32              `json:"installment_num"`
	TotalInstallments int32              `json:"total_installments"`
	AmountDue         pgtype.Numeric     `json:"amount_due"`
	InterestAmount    pgtype.Numeric     `json:"interest_amount"`
	PrincipalAmount   pgtype.Numeric     `json:"principal_amount"`
	AmountPaid        pgtype.Numeric     `json:"amount_paid"`
	Paid              bool               `json:"paid"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type ExpenseMonthlyStatus struct {
	ID         uuid.UUID          `json:"id"`
	ExpenseID  uuid.UUID          `json:"expense_id"`
	Month      pgtype.Date        `json:"month"`
	Paid       bool               `json:"paid"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	AmountPaid pgtype.Numeric     `json:"amount_paid"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  time.Time          `json:"created_at"`
}

type InviteToken struct {
	ID        uuid.UUID `json:"id"`
	Token     string    `json:"token"`
	CreatedBy uuid.UUID `json:"created_by"`
	Used      bool      `json:"used"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type MonthlySummary struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Month             pgtype.Date    `json:"month"`
	TotalIncome       pgtype.Numeric `json:"total_income"`
	IncomeBreakdown   []byte         `json:"income_breakdown"`
	TotalExpenses     pgtype.Numeric `json:"total_expenses"`
	ExpenseBreakdown  []byte         `json:"expense_breakdown"`
	TotalDebtPayments pgtype.Numeric `json:"total_debt_payments"`
	DebtBreakdown     []byte         `json:"debt_breakdown"`
	TotalObligations  pgtype.Numeric `json:"total_obligations"`
	NetBalance        pgtype.Numeric `json:"net_balance"`
	ProjectedIncome   pgtype.Numeric `json:"projected_income"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type RecurringExpense struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Frequency   string         `json:"frequency"`
	DueDay      pgtype.Int4    `json:"due_day"`
	Status      string         `json:"status"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	CategoryID         pgtype.UUID    `json:"category_id"`
	Type               string         `json:"type"`
	Amount             pgtype.Numeric `json:"amount"`
	Description        pgtype.Text    `json:"description"`
	Source             pgtype.Text    `json:"source"`
	ReferenceDate      pgtype.Date    `json:"reference_date"`
	IsRecurring        bool           `json:"is_recurring"`
	RecurringExpenseID pgtype.UUID    `json:"recurring_expense_id"`
	CreatedAt          time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	EmailHash    string      `json:"email_hash"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	Role         string      `json:"role"`
	Active       bool        `json:"active"`
	SuperAdmin   bool        `json:"super_admin"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
