// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monthly_summary.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMonthlySummary = `-- name: DeleteMonthlySummary :exec
DELETE FROM monthly_summary WHERE id = $1
`

func (q *Queries) DeleteMonthlySummary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonthlySummary, id)
	return err
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT id, user_id, month, total_income, income_breakdown, total_expenses, expense_breakdown, total_debt_payments, debt_breakdown, total_obligations, net_balance, projected_income, created_at, updated_at FROM monthly_summary WHERE user_id = $1 AND month = $2
`

type GetMonthlySummaryParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Month  pgtype.Date `json:"month"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (MonthlySummary, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary, arg.UserID, arg.Month)
	var i MonthlySummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.TotalIncome,
		&i.IncomeBreakdown,
		&i.TotalExpenses,
		&i.ExpenseBreakdown,
		&i.TotalDebtPayments,
		&i.DebtBreakdown,
		&i.TotalObligations,
		&i.NetBalance,
		&i.ProjectedIncome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMonthlySummariesByYear = `-- name: ListMonthlySummariesByYear :many
SELECT id, user_id, month, total_income, income_breakdown, total_expenses, expense_breakdown, total_debt_payments, debt_breakdown, total_obligations, net_balance, projected_income, created_at, updated_at FROM monthly_summary
WHERE user_id = $1
  AND month >= $2
  AND month < $3
ORDER BY month DESC
`

type ListMonthlySummariesByYearParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Month   pgtype.Date `json:"month"`
	Month_2 pgtype.Date `json:"month_2"`
}

func (q *Queries) ListMonthlySummariesByYear(ctx context.Context, arg ListMonthlySummariesByYearParams) ([]MonthlySummary, error) {
	rows, err := q.db.Query(ctx, listMonthlySummariesByYear, arg.UserID, arg.Month, arg.Month_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlySummary{}
	for rows.Next() {
		var i MonthlySummary
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Month,
			&i.TotalIncome,
			&i.IncomeBreakdown,
			&i.TotalExpenses,
			&i.ExpenseBreakdown,
			&i.TotalDebtPayments,
			&i.DebtBreakdown,
			&i.TotalObligations,
			&i.NetBalance,
			&i.ProjectedIncome,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlySummary = `-- name: UpsertMonthlySummary :one
INSERT INTO monthly_summary (user_id, month, total_income, income_breakdown,
                             total_expenses, expense_breakdown,
                             total_debt_payments, debt_breakdown,
                             total_obligations, net_balance, projected_income)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, month)
DO UPDATE SET total_income = COALESCE($3, monthly_summary.total_income),
              income_breakdown = COALESCE($4, monthly_summary.income_breakdown),
              total_expenses = COALESCE($5, monthly_summary.total_expenses),
              expense_breakdown = COALESCE($6, monthly_summary.expense_breakdown),
              total_debt_payments = COALESCE($7, monthly_summary.total_debt_payments),
              debt_breakdown = COALESCE($8, monthly_summary.debt_breakdown),
              total_obligations = COALESCE($9, monthly_summary.total_obligations),
              net_balance = COALESCE($10, monthly_summary.net_balance),
              projected_income = COALESCE($11, monthly_summary.projected_income),
              updated_at = now()
RETURNING id, user_id, month, total_income, income_breakdown, total_expenses, expense_breakdown, total_debt_payments, debt_breakdown, total_obligations, net_balance, projected_income, created_at, updated_at
`

type UpsertMonthlySummaryParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	Month             pgtype.Date    `json:"month"`
	TotalIncome       pgtype.Numeric `json:"total_income"`
	IncomeBreakdown   []byte         `json:"income_breakdown"`
	TotalExpenses     pgtype.Numeric `json:"total_expenses"`
	ExpenseBreakdown  []byte         `json:"expense_breakdown"`
	TotalDebtPayments pgtype.Numeric `json:"total_debt_payments"`
	DebtBreakdown     []byte         `json:"debt_breakdown"`
	TotalObligations  pgtype.Numeric `json:"total_obligations"`
	NetBalance        pgtype.Numeric `json:"net_balance"`
	ProjectedIncome   pgtype.Numeric `json:"projected_income"`
}

func (q *Queries) UpsertMonthlySummary(ctx context.Context, arg UpsertMonthlySummaryParams) (MonthlySummary, error) {
	row := q.db.QueryRow(ctx, upsertMonthlySummary,
		arg.UserID,
		arg.Month,
		arg.TotalIncome,
		arg.IncomeBreakdown,
		arg.TotalExpenses,
		arg.ExpenseBreakdown,
		arg.TotalDebtPayments,
		arg.DebtBreakdown,
		arg.TotalObligations,
		arg.NetBalance,
		arg.ProjectedIncome,
	)
	var i MonthlySummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Month,
		&i.TotalIncome,
		&i.IncomeBreakdown,
		&i.TotalExpenses,
		&i.ExpenseBreakdown,
		&i.TotalDebtPayments,
		&i.DebtBreakdown,
		&i.TotalObligations,
		&i.NetBalance,
		&i.ProjectedIncome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
