// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupExpiredInviteTokens(ctx context.Context) error
	CountUsers(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	CreateDebtMonthlyStatus(ctx context.Context, arg CreateDebtMonthlyStatusParams) (DebtMonthlyStatus, error)
	CreateExpenseMonthlyStatus(ctx context.Context, arg CreateExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error)
	CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error)
	CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteDebt(ctx context.Context, id uuid.UUID) error
	DeleteDebtMonthlyStatus(ctx context.Context, id uuid.UUID) error
	DeleteExpenseMonthlyStatus(ctx context.Context, id uuid.UUID) error
	DeleteInviteToken(ctx context.Context, id uuid.UUID) error
	DeleteMonthlySummary(ctx context.Context, id uuid.UUID) error
	DeleteRecurringExpense(ctx context.Context, id uuid.UUID) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetDebtByID(ctx context.Context, id uuid.UUID) (Debt, error)
	GetDebtMonthlyStatus(ctx context.Context, arg GetDebtMonthlyStatusParams) (DebtMonthlyStatus, error)
	GetExpenseMonthlyStatus(ctx context.Context, arg GetExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error)
	GetInviteToken(ctx context.Context, token string) (InviteToken, error)
	GetInviteTokenByID(ctx context.Context, id uuid.UUID) (InviteToken, error)
	GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) (MonthlySummary, error)
	GetRecurringExpenseByID(ctx context.Context, id uuid.UUID) (RecurringExpense, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetUserByEmailHash(ctx context.Context, emailHash string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveDebtsByUserID(ctx context.Context, userID uuid.UUID) ([]Debt, error)
	ListActiveRecurringExpensesByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringExpense, error)
	ListAllInviteTokens(ctx context.Context) ([]ListAllInviteTokensRow, error)
	ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error)
	ListCategoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error)
	ListDebtMonthlyStatusByDebtID(ctx context.Context, debtID uuid.UUID) ([]DebtMonthlyStatus, error)
	ListDebtMonthlyStatusByMonth(ctx context.Context, month pgtype.Date) ([]DebtMonthlyStatus, error)
	ListUnpaidByUserIDAndDateRange(ctx context.Context, arg ListUnpaidByUserIDAndDateRangeParams) ([]DebtMonthlyStatus, error)
	ListDebtsByUserID(ctx context.Context, userID uuid.UUID) ([]Debt, error)
	ListExpenseMonthlyStatusByExpenseID(ctx context.Context, expenseID uuid.UUID) ([]ExpenseMonthlyStatus, error)
	ListExpenseMonthlyStatusByMonth(ctx context.Context, month pgtype.Date) ([]ExpenseMonthlyStatus, error)
	ListInviteTokensByCreator(ctx context.Context, createdBy uuid.UUID) ([]InviteToken, error)
	ListMonthlySummariesByYear(ctx context.Context, arg ListMonthlySummariesByYearParams) ([]MonthlySummary, error)
	ListRecurringExpensesByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringExpense, error)
	ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error)
	ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error)
	ListTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]Transaction, error)
	ListTransactionsByUserIDAndMonth(ctx context.Context, arg ListTransactionsByUserIDAndMonthParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkDebtMonthAsPaid(ctx context.Context, arg MarkDebtMonthAsPaidParams) (DebtMonthlyStatus, error)
	MarkExpenseMonthAsPaid(ctx context.Context, arg MarkExpenseMonthAsPaidParams) (ExpenseMonthlyStatus, error)
	MarkInviteTokenAsUsed(ctx context.Context, id uuid.UUID) (InviteToken, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateDebtCurrentInstallment(ctx context.Context, arg UpdateDebtCurrentInstallmentParams) (Debt, error)
	UpdateDebtMonthlyStatus(ctx context.Context, arg UpdateDebtMonthlyStatusParams) (DebtMonthlyStatus, error)
	UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertExpenseMonthlyStatus(ctx context.Context, arg UpsertExpenseMonthlyStatusParams) (ExpenseMonthlyStatus, error)
	UpsertMonthlySummary(ctx context.Context, arg UpsertMonthlySummaryParams) (MonthlySummary, error)
}

var _ Querier = (*Queries)(nil)
