// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_expenses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (user_id, category_id, name, description, amount,
                                frequency, due_day, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, category_id, name, description, amount, frequency, due_day, status, start_date, end_date, created_at, updated_at
`

type CreateRecurringExpenseParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Frequency   string         `json:"frequency"`
	DueDay      pgtype.Int4    `json:"due_day"`
	Status      string         `json:"status"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Frequency,
		arg.DueDay,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Frequency,
		&i.DueDay,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses WHERE id = $1
`

func (q *Queries) DeleteRecurringExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpense, id)
	return err
}

const getRecurringExpenseByID = `-- name: GetRecurringExpenseByID :one
SELECT id, user_id, category_id, name, description, amount, frequency, due_day, status, start_date, end_date, created_at, updated_at FROM recurring_expenses WHERE id = $1
`

func (q *Queries) GetRecurringExpenseByID(ctx context.Context, id uuid.UUID) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByID, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Frequency,
		&i.DueDay,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRecurringExpensesByUserID = `-- name: ListActiveRecurringExpensesByUserID :many
SELECT id, user_id, category_id, name, description, amount, frequency, due_day, status, start_date, end_date, created_at, updated_at FROM recurring_expenses WHERE user_id = $1 AND status = 'active' ORDER BY name
`

func (q *Queries) ListActiveRecurringExpensesByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.Frequency,
			&i.DueDay,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpensesByUserID = `-- name: ListRecurringExpensesByUserID :many
SELECT id, user_id, category_id, name, description, amount, frequency, due_day, status, start_date, end_date, created_at, updated_at FROM recurring_expenses WHERE user_id = $1 ORDER BY name
`

func (q *Queries) ListRecurringExpensesByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listRecurringExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.Frequency,
			&i.DueDay,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    amount = COALESCE($4, amount),
    frequency = COALESCE($5, frequency),
    due_day = COALESCE($6, due_day),
    status = COALESCE($7, status),
    end_date = COALESCE($8, end_date),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, category_id, name, description, amount, frequency, due_day, status, start_date, end_date, created_at, updated_at
`

type UpdateRecurringExpenseParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Frequency   string         `json:"frequency"`
	DueDay      pgtype.Int4    `json:"due_day"`
	Status      string         `json:"status"`
	EndDate     pgtype.Date    `json:"end_date"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Frequency,
		arg.DueDay,
		arg.Status,
		arg.EndDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.Frequency,
		&i.DueDay,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
