// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, category_id, type, amount, description, source,
                          reference_date, is_recurring, recurring_expense_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at
`

type CreateTransactionParams struct {
	UserID             uuid.UUID      `json:"user_id"`
	CategoryID         pgtype.UUID    `json:"category_id"`
	Type               string         `json:"type"`
	Amount             pgtype.Numeric `json:"amount"`
	Description        pgtype.Text    `json:"description"`
	Source             pgtype.Text    `json:"source"`
	ReferenceDate      pgtype.Date    `json:"reference_date"`
	IsRecurring        bool           `json:"is_recurring"`
	RecurringExpenseID pgtype.UUID    `json:"recurring_expense_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Source,
		arg.ReferenceDate,
		arg.IsRecurring,
		arg.RecurringExpenseID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Source,
		&i.ReferenceDate,
		&i.IsRecurring,
		&i.RecurringExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Source,
		&i.ReferenceDate,
		&i.IsRecurring,
		&i.RecurringExpenseID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at FROM transactions
WHERE user_id = $1
  AND reference_date >= $2
  AND reference_date <= $3
ORDER BY reference_date DESC
`

type ListTransactionsByDateRangeParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	ReferenceDate   pgtype.Date `json:"reference_date"`
	ReferenceDate_2 pgtype.Date `json:"reference_date_2"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange, arg.UserID, arg.ReferenceDate, arg.ReferenceDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Source,
			&i.ReferenceDate,
			&i.IsRecurring,
			&i.RecurringExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at FROM transactions
WHERE user_id = $1 AND type = $2
ORDER BY reference_date DESC
`

type ListTransactionsByTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Source,
			&i.ReferenceDate,
			&i.IsRecurring,
			&i.RecurringExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserID = `-- name: ListTransactionsByUserID :many
SELECT id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at FROM transactions WHERE user_id = $1 ORDER BY reference_date DESC, created_at DESC
`

func (q *Queries) ListTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Source,
			&i.ReferenceDate,
			&i.IsRecurring,
			&i.RecurringExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserIDAndMonth = `-- name: ListTransactionsByUserIDAndMonth :many
SELECT id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at FROM transactions
WHERE user_id = $1
  AND reference_date >= $2
  AND reference_date < $3
ORDER BY reference_date DESC
`

type ListTransactionsByUserIDAndMonthParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	ReferenceDate   pgtype.Date `json:"reference_date"`
	ReferenceDate_2 pgtype.Date `json:"reference_date_2"`
}

func (q *Queries) ListTransactionsByUserIDAndMonth(ctx context.Context, arg ListTransactionsByUserIDAndMonthParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserIDAndMonth, arg.UserID, arg.ReferenceDate, arg.ReferenceDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Source,
			&i.ReferenceDate,
			&i.IsRecurring,
			&i.RecurringExpenseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = COALESCE($3, category_id),
    amount = COALESCE($4, amount),
    description = COALESCE($5, description),
    source = COALESCE($6, source),
    reference_date = COALESCE($7, reference_date)
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, type, amount, description, source, reference_date, is_recurring, recurring_expense_id, created_at
`

type UpdateTransactionParams struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	CategoryID    pgtype.UUID    `json:"category_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Description   pgtype.Text    `json:"description"`
	Source        pgtype.Text    `json:"source"`
	ReferenceDate pgtype.Date    `json:"reference_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Source,
		arg.ReferenceDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Source,
		&i.ReferenceDate,
		&i.IsRecurring,
		&i.RecurringExpenseID,
		&i.CreatedAt,
	)
	return i, err
}
