// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_hash, password_hash, full_name, phone, role, super_admin)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	EmailHash    string      `json:"email_hash"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	Role         string      `json:"role"`
	SuperAdmin   bool        `json:"super_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailHash,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.SuperAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at FROM users WHERE email_hash = $1
`

func (q *Queries) GetUserByEmailHash(ctx context.Context, emailHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailHash, emailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailHash,
			&i.PasswordHash,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.Active,
			&i.SuperAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET active = $2, updated_at = now() WHERE id = $1 RETURNING id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at
`

type SetUserActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.Active)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = COALESCE($2, email),
    email_hash = COALESCE($3, email_hash),
    full_name = COALESCE($4, full_name),
    phone = COALESCE($5, phone),
    role = COALESCE($6, role),
    active = COALESCE($7, active),
    updated_at = now()
WHERE id = $1
RETURNING id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	Email     string      `json:"email"`
	EmailHash string      `json:"email_hash"`
	FullName  string      `json:"full_name"`
	Phone     pgtype.Text `json:"phone"`
	Role      string      `json:"role"`
	Active    bool        `json:"active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.Active,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1 RETURNING id, email, email_hash, password_hash, full_name, phone, role, active, super_admin, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailHash,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.Active,
		&i.SuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
